CREATE TABLE [dbo].[Registration] (
    [id]             INT              IDENTITY (1, 1) NOT NULL,
    [username]       NVARCHAR (256)   NULL,
    [firstNAme]      NVARCHAR (256)   NULL,
    [lastName]       NVARCHAR (256)   NULL,
    [birthDate]      DATETIME         NULL,
    [education]      VARCHAR (100)    NULL,
    [medications]    BIT              NULL,
    [medName]        VARCHAR (100)    NULL,
    [gender]         VARCHAR (100)    NULL,
    [hand]           VARCHAR (100)    NULL,
    [brainActivity]  VARCHAR (100)    NULL,
    [ethnisity]      VARCHAR (100)    NULL,
    [language]       VARCHAR (100)    NULL,
    [headInjury]     BIT              NULL,
    [headInjAmount]  VARCHAR (100)    NULL,
    [selfEsteem]     VARCHAR (100)    NULL,
    [exercise]       VARCHAR (100)    NULL,
    [selfHealth]     VARCHAR (100)    NULL,
    [profileFilled]  BIT              NULL,
    [userId]         UNIQUEIDENTIFIER NULL,
    [income]         VARCHAR (100)    NULL,
    [disclamerField] BIT              NULL,
    [providerId]     INT              NULL,
    [showResults]    BIT              NULL,
    CONSTRAINT [PK_Registration] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_Registration_Provider] FOREIGN KEY ([providerId]) REFERENCES [dbo].[Provider] ([id]),
    CONSTRAINT [FK_Registration_Registration] FOREIGN KEY ([userId]) REFERENCES [dbo].[aspnet_Membership] ([UserId]) ON DELETE CASCADE ON UPDATE CASCADE
);

