//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Tests.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CogQuest_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CogQuest_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestSite.Tests.App_LocalResources.CogQuest.aspx", typeof(CogQuest_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View User Manual.
        /// </summary>
        internal static string btnManual_Text {
            get {
                return ResourceManager.GetString("btnManual.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string downloadBtn_Text {
            get {
                return ResourceManager.GetString("downloadBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Examples.
        /// </summary>
        internal static string examplesTitle_Text {
            get {
                return ResourceManager.GetString("examplesTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create questionnaire in any language.
        /// </summary>
        internal static string img1DescrSpan1_Text {
            get {
                return ResourceManager.GetString("img1DescrSpan1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from 8 types of questions.
        /// </summary>
        internal static string img1DescrSpan2_Text {
            get {
                return ResourceManager.GetString("img1DescrSpan2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your header color.
        /// </summary>
        internal static string img1DescrSpan3_Text {
            get {
                return ResourceManager.GetString("img1DescrSpan3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set fonts.
        /// </summary>
        internal static string img1DescrSpan4_Text {
            get {
                return ResourceManager.GetString("img1DescrSpan4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email as an attachment to anybody in the world.
        /// </summary>
        internal static string img1DescrSpan5_Text {
            get {
                return ResourceManager.GetString("img1DescrSpan5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your own questionnaire. As many as you would like.
        /// </summary>
        internal static string img1Title_Text {
            get {
                return ResourceManager.GetString("img1Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create scale of any size.
        /// </summary>
        internal static string img2DescrSpan1_Text {
            get {
                return ResourceManager.GetString("img2DescrSpan1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set description text.
        /// </summary>
        internal static string img2DescrSpan2_Text {
            get {
                return ResourceManager.GetString("img2DescrSpan2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set font size.
        /// </summary>
        internal static string img2DescrSpan3_Text {
            get {
                return ResourceManager.GetString("img2DescrSpan3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support multilane description.
        /// </summary>
        internal static string img2DescrSpan4_Text {
            get {
                return ResourceManager.GetString("img2DescrSpan4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Likert scale question.
        /// </summary>
        internal static string img2Title_Text {
            get {
                return ResourceManager.GetString("img2Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Date Format Question for birthdates or events.
        /// </summary>
        internal static string img3DescrSpan1_Text {
            get {
                return ResourceManager.GetString("img3DescrSpan1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Combo Box question for multiple choice single option answer.
        /// </summary>
        internal static string img3DescrSpan2_Text {
            get {
                return ResourceManager.GetString("img3DescrSpan2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works with words or numbers.
        /// </summary>
        internal static string img3DescrSpan3_Text {
            get {
                return ResourceManager.GetString("img3DescrSpan3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up the fonts size.
        /// </summary>
        internal static string img3DescrSpan4_Text {
            get {
                return ResourceManager.GetString("img3DescrSpan4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Date and Combo Box question.
        /// </summary>
        internal static string img3Title_Text {
            get {
                return ResourceManager.GetString("img3Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select between Radiobutton and CheckBox type question.
        /// </summary>
        internal static string img4DescrSpan1_Text {
            get {
                return ResourceManager.GetString("img4DescrSpan1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set text font.
        /// </summary>
        internal static string img4DescrSpan2_Text {
            get {
                return ResourceManager.GetString("img4DescrSpan2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set answers direction.
        /// </summary>
        internal static string img4DescrSpan3_Text {
            get {
                return ResourceManager.GetString("img4DescrSpan3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Radiobutton and CheckBox.
        /// </summary>
        internal static string img4Title_Text {
            get {
                return ResourceManager.GetString("img4Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text for participant to read.
        /// </summary>
        internal static string img5DescrSpan1_Text {
            get {
                return ResourceManager.GetString("img5DescrSpan1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text will be hidden after its read.
        /// </summary>
        internal static string img5DescrSpan2_Text {
            get {
                return ResourceManager.GetString("img5DescrSpan2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up any number of any type questions for the participant to answer.
        /// </summary>
        internal static string img5DescrSpan3_Text {
            get {
                return ResourceManager.GetString("img5DescrSpan3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Vignette Question.
        /// </summary>
        internal static string img5Title_Text {
            get {
                return ResourceManager.GetString("img5Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import images as part of the question.
        /// </summary>
        internal static string img6DescrSpan1_Text {
            get {
                return ResourceManager.GetString("img6DescrSpan1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import one large image or multiple small ones.
        /// </summary>
        internal static string img6DescrSpan2_Text {
            get {
                return ResourceManager.GetString("img6DescrSpan2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 sizes available.
        /// </summary>
        internal static string img6DescrSpan3_Text {
            get {
                return ResourceManager.GetString("img6DescrSpan3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align vertically or horisontally.
        /// </summary>
        internal static string img6DescrSpan4_Text {
            get {
                return ResourceManager.GetString("img6DescrSpan4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Image Question.
        /// </summary>
        internal static string img6Title_Text {
            get {
                return ResourceManager.GetString("img6Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have ability to save filled out questionnaire using question text or Variable name for easy import to any Database.
        /// </summary>
        internal static string img7DescrSpan1_Text {
            get {
                return ResourceManager.GetString("img7DescrSpan1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as a simple text file to store as a hard copy.
        /// </summary>
        internal static string img7DescrSpan2_Text {
            get {
                return ResourceManager.GetString("img7DescrSpan2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is not stored on the device to ensure patient&apos;s privacy.
        /// </summary>
        internal static string img7DescrSpan3_Text {
            get {
                return ResourceManager.GetString("img7DescrSpan3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Save either by question name or variable name.
        /// </summary>
        internal static string img7Title_Text {
            get {
                return ResourceManager.GetString("img7Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the ability to enter the correct answer and score the test right after.
        /// </summary>
        internal static string img8DescrSpan1_Text {
            get {
                return ResourceManager.GetString("img8DescrSpan1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import one large image or multiple small ones.
        /// </summary>
        internal static string img8DescrSpan2_Text {
            get {
                return ResourceManager.GetString("img8DescrSpan2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print out scored results.
        /// </summary>
        internal static string img8DescrSpan3_Text {
            get {
                return ResourceManager.GetString("img8DescrSpan3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Score the test.
        /// </summary>
        internal static string img8Title_Text {
            get {
                return ResourceManager.GetString("img8Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have ability to export test to html file.
        /// </summary>
        internal static string img9DescrSpan1_Text {
            get {
                return ResourceManager.GetString("img9DescrSpan1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send this file to friends or take it home.
        /// </summary>
        internal static string img9DescrSpan2_Text {
            get {
                return ResourceManager.GetString("img9DescrSpan2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add generated test to your site.
        /// </summary>
        internal static string img9DescrSpan3_Text {
            get {
                return ResourceManager.GetString("img9DescrSpan3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass it and print results to excell file.
        /// </summary>
        internal static string img9DescrSpan4_Text {
            get {
                return ResourceManager.GetString("img9DescrSpan4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Export to HTML.
        /// </summary>
        internal static string img9Title_Text {
            get {
                return ResourceManager.GetString("img9Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Key.
        /// </summary>
        internal static string key_Text {
            get {
                return ResourceManager.GetString("key.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;CogQuest Quesionnaire desktop tool allows to create a series of questions to gather any needed inforamtion from/about participants. It has 7 types of questions, including Date and Dropdown. CogQuest allows storing data in text file for printing or Excel Document for easy export to SPSS.&lt;/p&gt;
        ///
        ///&lt;p&gt;You can create multiple choice questions, Likert scale questions, long open-ended questions, short answer questions, etc. This is ideal for research labs. You can email a demographic questionnaire to a scheduled [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mainDescription_Text {
            get {
                return ResourceManager.GetString("mainDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CogQuest Simple Questionnaire.
        /// </summary>
        internal static string mainTitle_Text {
            get {
                return ResourceManager.GetString("mainTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string navbar_about_Text {
            get {
                return ResourceManager.GetString("navbar_about.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string navbar_home_Text {
            get {
                return ResourceManager.GetString("navbar_home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string navbar_logIn_Text {
            get {
                return ResourceManager.GetString("navbar_logIn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string navbar_logOut_Text {
            get {
                return ResourceManager.GetString("navbar_logOut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string navbar_profile_Text {
            get {
                return ResourceManager.GetString("navbar_profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychological Questionnaire, Cognitive Test Online Practice, Cognitive Ability Test Online.
        /// </summary>
        internal static string pageTitle_Text {
            get {
                return ResourceManager.GetString("pageTitle.Text", resourceCulture);
            }
        }
    }
}
